import{t,getLanguage}from'./i18n.js';
import{escape as e}from'./domain.js';
export const stationUrl='https://snakefreak85.github.io/Arbeitszeiterfassung/#clock=zeitwerk-arbeitszeiterfassung-8ca47';
export function validStation(value){try{const url=new URL(value),expected=new URL(stationUrl);return url.origin===expected.origin&&url.pathname===expected.pathname&&url.hash===expected.hash&&!url.search;}catch{return false;}}
export function qrSvg(){const qr=window.qrcode(0,'M');qr.addData(stationUrl);qr.make();return qr.createSvgTag({cellSize:4,margin:16,scalable:true});}
export function printMarkup(format,svg){
 const card=format==='card';
 const steps=[t('Zeitwerk öffnen und anmelden.'),t('„QR-Code scannen“ öffnen und diesen Code scannen.'),t('Arbeitsbeginn, Pause starten, Pause beenden oder Feierabend auswählen.'),t('Bestätigung abwarten. Die Uhrzeit wird automatisch gespeichert.')];
 return `<!doctype html><html lang="${getLanguage()}"><head><meta charset="utf-8"><title>Zeitwerk · ${e(t('QR-Code für Zeiterfassung'))}</title><style>
 @page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#163d36;background:#eee}section{background:white;margin:12px auto;position:relative;overflow:hidden}h1,h2,p{margin:0}svg{display:block;width:100%;height:100%}ol{padding-left:1.4em}li{margin:0 0 12px;line-height:1.45}.a4{width:210mm;height:297mm;padding:23mm}.a4 h1{font-size:34pt}.a4 h2{font-size:20pt;margin:7mm 0}.a4 .qr{width:105mm;height:105mm;margin:8mm auto}.a4 ol{font-size:13pt}.a4 .url{font-size:10pt;overflow-wrap:anywhere}.sheet{width:210mm;height:297mm;display:grid;place-items:center}.card{width:85mm;height:55mm;border:.3mm dashed #777;padding:4mm}.card.front{display:flex;align-items:center;gap:4mm}.card .qr{width:43mm;height:43mm;flex-shrink:0}.card h1{font-size:15pt}.card h2{font-size:11pt}.card p,.card ol{font-size:8pt;line-height:1.3}.card ol{margin:3mm 0 0}.card li{margin-bottom:1mm}.card .url{font-size:6pt;overflow-wrap:anywhere;margin-top:2mm}.controls{text-align:center;padding:20px;font-size:14px}button{padding:12px 20px;cursor:pointer}
 @media print{body{background:white}.controls{display:none}section{margin:0;break-after:page}section:last-child{break-after:auto}.card{break-after:auto}}
 </style></head><body><div class="controls"><p>${e(t(card?'Beidseitig drucken: an der langen Kante wenden. Originalgröße / 100 % wählen. Beide Seiten liegen mittig auf A4; anschließend ausschneiden.':'A4 · Originalgröße / 100 % wählen.'))}</p><button onclick="window.print()">${e(t('Drucken'))}</button></div>${card?`<section class="sheet"><div class="card front"><div class="qr">${svg}</div><div><h1>Zeitwerk</h1><p>${e(t('QR-Code für Zeiterfassung'))}</p></div></div></section><section class="sheet"><div class="card back"><h2>${e(t('So erfasst du deine Zeit'))}</h2><ol>${steps.map(s=>`<li>${e(s)}</li>`).join('')}</ol><p class="url">snakefreak85.github.io/Arbeitszeiterfassung/</p></div></section>`:`<section class="a4"><h1>Zeitwerk</h1><h2>${e(t('QR-Code für Zeiterfassung'))}</h2><div class="qr">${svg}</div><h2>${e(t('So erfasst du deine Zeit'))}</h2><ol>${steps.map(s=>`<li>${e(s)}</li>`).join('')}</ol><p class="url">https://snakefreak85.github.io/Arbeitszeiterfassung/</p></section>`}</body></html>`;
}
export function openPrint(format){const popup=window.open('','_blank');if(!popup)throw Error('Bitte Pop-ups zum Öffnen der Druckvorlage erlauben.');popup.document.open();popup.document.write(printMarkup(format,qrSvg()));popup.document.close();popup.focus();}
let dialog=null,stream=null,tick=null,generation=0;
function stopCamera(){clearTimeout(tick);tick=null;if(stream)stream.getTracks().forEach(track=>track.stop());stream=null;}
export function closeScanner(){generation++;stopCamera();if(dialog){dialog.close();dialog.remove();dialog=null;}}
export function chooseClock(actions,name,onAction){closeScanner();dialog=document.createElement('dialog');dialog.className='scan-dialog';dialog.innerHTML=`<h3>${e(t('QR-Code erkannt'))}</h3><p>${e(name)}</p><div class="scan-actions">${Object.entries(actions).map(([key,{label,enabled}])=>`<button class="primary" data-clock="${key}" ${enabled?'':'disabled'}>${e(label)}</button>`).join('')}</div><p id="clock-result" role="status"></p><button data-close>${e(t('Abbrechen'))}</button>`;document.body.append(dialog);dialog.showModal();dialog.querySelector('[data-close]').onclick=closeScanner;dialog.oncancel=closeScanner;let busy=false;dialog.querySelectorAll('[data-clock]').forEach(button=>button.onclick=async()=>{if(busy)return;busy=true;const current=dialog;current.querySelectorAll('button').forEach(b=>b.disabled=true);try{await onAction(button.dataset.clock);closeScanner();}catch(err){if(current.isConnected){current.querySelector('#clock-result').textContent=err.message;current.querySelector('[data-close]').disabled=false;}/* Rescan for fresh state before trying again. */}});}
export async function startScanner(onScan){
 closeScanner();const mine=++generation;dialog=document.createElement('dialog');dialog.className='scan-dialog';dialog.innerHTML=`<h3>${e(t('QR-Code scannen'))}</h3><p>${e(t('Halte die Kamera auf den Zeitwerk-QR-Code im Betrieb.'))}</p><video autoplay muted playsinline></video><p class="scan-status" role="status">${e(t('Kamera wird geöffnet …'))}</p><label>${e(t('Alternativ QR-Foto auswählen'))}<input type="file" accept="image/*" capture="environment"></label><button data-close>${e(t('Abbrechen'))}</button>`;document.body.append(dialog);dialog.showModal();const current=dialog,video=current.querySelector('video'),status=current.querySelector('.scan-status'),canvas=document.createElement('canvas'),context=canvas.getContext('2d',{willReadFrequently:true});current.querySelector('[data-close]').onclick=closeScanner;current.oncancel=closeScanner;
 let found=false;const consume=code=>{if(found||mine!==generation||!code)return;if(!validStation(code.data)){status.textContent=t('Dieser QR-Code gehört nicht zu Zeitwerk.');return;}found=true;closeScanner();onScan();};
 current.querySelector('input').onchange=async event=>{const file=event.target.files[0];if(!file)return;const url=URL.createObjectURL(file);try{const picture=new Image();picture.src=url;await picture.decode();if(mine!==generation)return;const scale=Math.min(1,1600/picture.naturalWidth);canvas.width=Math.round(picture.naturalWidth*scale);canvas.height=Math.round(picture.naturalHeight*scale);context.drawImage(picture,0,0,canvas.width,canvas.height);const code=window.jsQR(context.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height);if(code)consume(code);else status.textContent=t('Kein QR-Code erkannt. Bitte erneut versuchen.');}catch{status.textContent=t('Das Bild konnte nicht gelesen werden.');}finally{URL.revokeObjectURL(url);}};
 try{
  if(!navigator.mediaDevices?.getUserMedia)throw Error('unsupported');const acquired=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});if(mine!==generation){acquired.getTracks().forEach(track=>track.stop());return;}stream=acquired;video.srcObject=stream;await video.play();status.textContent=t('QR-Code im Kamerabild ausrichten.');
  const scan=()=>{if(mine!==generation)return;try{if(video.readyState>=2&&video.videoWidth){const scale=Math.min(1,800/video.videoWidth);canvas.width=Math.round(video.videoWidth*scale);canvas.height=Math.round(video.videoHeight*scale);context.drawImage(video,0,0,canvas.width,canvas.height);consume(window.jsQR(context.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height,{inversionAttempts:'dontInvert'}));}}catch{status.textContent=t('Kein QR-Code erkannt. Bitte erneut versuchen.');}if(mine===generation)tick=setTimeout(scan,180);};scan();
 }catch(err){if(mine===generation){stopCamera();status.textContent=t(err.name==='NotAllowedError'?'Kamerazugriff verweigert. Bitte in den Browsereinstellungen erlauben oder ein QR-Foto auswählen.':'Kamera nicht verfügbar. Bitte ein QR-Foto auswählen oder manuell erfassen.');}}
}
if(typeof document!=='undefined'){document.addEventListener('visibilitychange',()=>{if(document.hidden)closeScanner();});window.addEventListener('pagehide',closeScanner);}
