import test from 'node:test';import assert from 'node:assert/strict';import{manageEmployee}from'../functions/employee-service.js';
class HttpsError extends Error{constructor(code,message){super(message);this.code=code}}
function setup(){const calls=[],data=new Map([['users/admin',{role:'admin',name:'Admin'}],['users/worker',{role:'employee',name:'Anna',daily:480}],['records/a',{person:'worker'}],['records/b',{person:'other'}],['requests/q',{person:'worker'}],['timers/worker',{person:'worker'}]]);const ref=path=>({path,get:async()=>({data:()=>structuredClone(data.get(path))}),update:async value=>{calls.push(['update',path,value]);data.set(path,{...data.get(path),...value})},delete:async()=>{calls.push(['delete',path]);data.delete(path)}});const db={
 doc:ref,
 collection:kind=>({where:(_key,_op,uid)=>({limit:n=>({get:async()=>{
  const rows=[...data].filter(([key,v])=>key.startsWith(kind+'/')&&v.person===uid).slice(0,n);
  return{empty:!rows.length,docs:rows.map(([path])=>({ref:ref(path)}))};
 }})})}),
 batch:()=>{const paths=[];return{delete:r=>paths.push(r.path),commit:async()=>paths.forEach(path=>data.delete(path))}}
};return{data,calls,db,HttpsError,getAuth:()=>({updateUser:async(...args)=>calls.push(['authUpdate',...args]),revokeRefreshTokens:async uid=>calls.push(['revoke',uid]),deleteUser:async uid=>calls.push(['authDelete',uid])})}}
const request=action=>({auth:{uid:'admin'},data:{uid:'worker',action}});
test('Employee management requires admin and protects administrator accounts',async()=>{const deps=setup();await assert.rejects(manageEmployee({data:request('archive').data},deps),e=>e.code==='unauthenticated');await assert.rejects(manageEmployee({...request('archive'),auth:{uid:'worker'}},deps),e=>e.code==='permission-denied');await assert.rejects(manageEmployee({...request('archive'),data:{uid:'admin',action:'delete',confirmation:'Admin'}},deps),e=>e.code==='failed-precondition');assert.equal(deps.calls.length,0)});
test('Archive blocks account, preserves records, and restore enables account',async()=>{const deps=setup();await manageEmployee(request('archive'),deps);assert.equal(deps.data.get('users/worker').archived,true);assert.ok(deps.data.has('records/a'));assert.ok(deps.calls.some(c=>c[0]==='authUpdate'&&c[2].disabled));await manageEmployee(request('restore'),deps);assert.equal(deps.data.get('users/worker').archived,false);assert.equal(deps.calls.at(-2)[2].disabled,false)});
test('Deletion requires name, removes only target data, and handles multiple batches',async()=>{const deps=setup();await assert.rejects(manageEmployee(request('delete'),deps),e=>e.code==='invalid-argument');assert.equal(deps.calls.length,0);for(let n=0;n<405;n++)deps.data.set('records/m'+n,{person:'worker'});await manageEmployee({...request('delete'),data:{...request('delete').data,confirmation:'Anna'}},deps);assert.deepEqual([...deps.data.keys()].sort(),['records/b','users/admin']);assert.ok(deps.calls.some(c=>c[0]==='authDelete'&&c[1]==='worker'));});
test('Failed deletion keeps blocked profile and can be retried',async()=>{const deps=setup(),auth=deps.getAuth();deps.getAuth=()=>({...auth,deleteUser:async()=>{throw Error('offline')}});await assert.rejects(manageEmployee({...request('delete'),data:{...request('delete').data,confirmation:'Anna'}},deps));assert.equal(deps.data.get('users/worker').deleting,true);await assert.rejects(manageEmployee(request('restore'),deps),e=>e.code==='failed-precondition');deps.getAuth=()=>auth;await manageEmployee({...request('delete'),data:{...request('delete').data,confirmation:'Anna'}},deps);assert.equal(deps.data.has('users/worker'),false)});
